# Site settings
title: Community
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software development, collaboration, community and similar stuff
baseurl: "/community" # the subpath of your site, e.g. /blog/
url: "http://maprohu.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  maprohu

# Build settings
markdown: kramdown
